=== ferusinfo/DTDBasics/conference.dtd
<!NOTATION GIF SYSTEM "image/gif">
<!NOTATION JPG SYSTEM "image/jpeg">
<!NOTATION PNG SYSTEM "image/png">

<!ELEMENT conference (cname,date,location,sponsors,agenda,speakers)*>
<!ATTLIST conference language CDATA #FIXED "EN">
<!ELEMENT cname %PCD;>

<!ELEMENT date (dstart,dend)?>
<!ELEMENT dstart (day,month,year)*>
<!ELEMENT day %PCD;>
<!ELEMENT month %PCD;>
<!ELEMENT year %PCD;>
<!ELEMENT dend (day,month,year)*>

<!ELEMENT location (venue)*>
<!ELEMENT venue (address)*>

<!ELEMENT address (place,district,city,street,gps)*>
<!ELEMENT place %PCD;>
<!ELEMENT district %PCD;>

<!ELEMENT city %PCD;>
<!ELEMENT street %PCD;>

<!ELEMENT gps (latitude,longtitude)*>
<!ELEMENT latitude %PCD;>
<!ELEMENT longtitude %PCD;>

<!ELEMENT sponsors (sponsor)+>
<!ELEMENT sponsor %PCD;>
<!ATTLIST sponsor type CDATA #REQUIRED>
<!ATTLIST sponsor sid ID #REQUIRED>

<!ELEMENT agenda (cday)*>
<!ELEMENT cday (lecture | comingsoon)*>
<!ATTLIST cday number (1|2) "1">

<!ELEMENT lecture (tstart,tend,title)*>
<!ATTLIST lecture speakerid IDREF #IMPLIED>
<!ELEMENT tstart %PCD;>
<!ELEMENT tend %PCD;>
<!ELEMENT title %PCD;>
<!ELEMENT comingsoon EMPTY>

<!ELEMENT speakers (speaker)*>
<!ELEMENT speaker ((name,photo?,twitter?) | comingsoon)*>
<!ATTLIST speaker speakerid ID #REQUIRED>

<!ELEMENT photo %PCD;>
<!ATTLIST photo type NOTATION (GIF | JPG | PNG) #IMPLIED>

<!ELEMENT name %PCD;>
<!ATTLIST name sex NMTOKEN #REQUIRED>

<!ELEMENT twitter (#PCDATA | emptytwitter)*>
<!ELEMENT emptytwitter EMPTY>

=== ferusinfo/DTDBasics/conference.xml
<?xml version="1.0" standalone="no" ?>

<!DOCTYPE conference SYSTEM "conference.dtd" [
	<!ENTITY officialTwitter "@mm_conf">
	<!ENTITY conferenceName "Mobile Mobile Conference">
	<!ENTITY TBA "To Be Announced">
	<!ENTITY % PCD "(#PCDATA)*" >
]>


<conference language="EN">
	<cname>&conferenceName;</cname>
	<date>
		<dstart>
			<day>18</day>
			<month>04</month>
			<year>2013</year>
		</dstart>
		<dend>
			<day>19</day>
			<month>04</month>
			<year>2013</year>
		</dend>
	</date>
	<location>
		<venue>
			<address>
				<place>Zabytkowa zajezdnia tramwajowa</place>
				<district>Kazimierz</district>
				<city>Krakow</city>
				<street>Sw. Wawrzynca 15</street>
				<gps>
					<latitude>50.0498</latitude>
					<longtitude>19.94715</longtitude>
				</gps>
			</address>
		</venue>
	</location>
	<sponsors>
		<sponsor type="Giant Zeppelin" sid="s01">hub:raum</sponsor>
		<sponsor type="Rocket Fighter" sid="s02">MailChimp</sponsor>
		<sponsor type="Videographer" sid="s03">Heroku</sponsor>
		<sponsor type="Automobile Pilot" sid="s04">New Relic</sponsor>
		<sponsor type="Music" sid="s05">Spotify</sponsor>
	</sponsors>
	<agenda>
		<cday number="1">
			<lecture speakerid="S1">
				<tstart>09:45</tstart>
				<tend>10:00</tend>
				<title>Hello and Welcome</title>
			</lecture>
			<lecture speakerid="S2">
				<tstart>10:00</tstart>
				<tend>10:45</tend>
				<title>Your idea sucks</title>
			</lecture>
			<lecture speakerid="S3">
				<tstart>11:00</tstart>
				<tend>11:45</tend>
				<title>&TBA;</title>
			</lecture>
		</cday>
		<cday number="2">
			<comingsoon/>
		</cday>
	</agenda>
	<speakers>
		<speaker speakerid="S1">
			<name sex="F">Ela Madej</name>
			<twitter>&officialTwitter;</twitter>
		</speaker>
		<speaker speakerid="S2">
			<name sex="M">Matteo Manferdini</name>
			<twitter />
		</speaker>
		<speaker speakerid="S3">
			<name sex="M">Brian Suda</name>
			<photo type="GIF">/photos/brian.gif</photo>
		</speaker>
		<speaker speakerid="S4">
			<comingsoon/>
		</speaker>
	</speakers>
</conference>
